site_name: Foxie Projects

theme: readthedocs

pages:
- Home: 'index.md'
- About: 'about.md'
- Learn-Along Documentation:
    - 'tmux': 'user-doc/tmux.md'
    - 'Travis CI': 'user-doc/travis.md'
    - 'python notes': 'user-doc/pylearn.md'
    - 'sql notes': 'user-doc/sql.md'
    - 'spark notes': 'user-doc/spark.md'

- Machine Learning:
    - 'Time Series Analysis': 'ml-doc/tsa.md'
