site_name: Foxie Projects

theme: readthedocs

pages:
- Home: 'index.md'
- About: 'about.md'
- User Documentation:
    - 'tmux': 'user-doc/tmux.md'
    - 'Travis CI': 'user-doc/travis.md'
    - 'python notes': 'user-doc/pylearn.md'

